# Generated by Django 2.0.5 on 2018-05-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, verbose_name='床名')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('DMGENDER', models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性')], max_length=100, null=True, verbose_name='性别')),
                ('DMAGE', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('DMHEIGHT', models.IntegerField(blank=True, help_text='(cm)', null=True, verbose_name='身高')),
                ('DMWEIGHT', models.FloatField(blank=True, help_text='(kg)', null=True, verbose_name='体重')),
                ('DMSTDTC', models.DateField(blank=True, null=True, verbose_name='入院日期')),
                ('DMENDTC', models.DateField(blank=True, null=True, verbose_name='出院日期')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.Bed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人基本信息',
            },
        ),
        migrations.CreateModel(
            name='PatientEX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('EXDOSE', models.CharField(max_length=200, verbose_name='每次用药剂量')),
                ('EXDATE', models.DateField(blank=True, null=True, verbose_name='给药日期')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.Bed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人用药记录',
            },
        ),
        migrations.CreateModel(
            name='PatientLB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('LBDATE', models.DateField(blank=True, null=True, verbose_name='检验时间')),
                ('LBCATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验分类')),
                ('LBSUCATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验子分类')),
                ('LBTEST', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验项目')),
                ('LBRESULT', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验结果')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.Bed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人化验放射检验报告',
            },
        ),
        migrations.CreateModel(
            name='PatientMH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('MHDATE', models.DateField(blank=True, null=True, verbose_name='问诊时间')),
                ('MHPAST', models.CharField(blank=True, max_length=200, null=True, verbose_name='既往史')),
                ('MHPERSONAL', models.CharField(blank=True, max_length=200, null=True, verbose_name='个人史')),
                ('MHFAMILY', models.CharField(blank=True, max_length=200, null=True, verbose_name='家族史')),
                ('MHSSTATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='现病史（入院病症）')),
                ('MHESTATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='现病史（出院病症）')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.Bed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人病史',
            },
        ),
        migrations.CreateModel(
            name='PatientPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('PETEST', models.CharField(max_length=200, verbose_name='体格检查名称')),
                ('PERESULT', models.CharField(max_length=200, verbose_name='体格检查结果')),
                ('PEDATE', models.DateField(verbose_name='体格检查日期')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.Bed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人体格检验',
            },
        ),
        migrations.CreateModel(
            name='PatientPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('PRFIGE', models.BooleanField(verbose_name='是否手术')),
                ('PRCATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='手术类别')),
                ('PRDATE', models.DateField(blank=True, null=True, verbose_name='手术时间')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.Bed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人手术状况',
            },
        ),
        migrations.CreateModel(
            name='PatientTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('TETEST', models.CharField(blank=True, max_length=200, null=True, verbose_name='每日检查项目')),
                ('TERESULT', models.CharField(blank=True, max_length=200, null=True, verbose_name='检查结果')),
                ('TEDATE', models.DateField(blank=True, null=True, verbose_name='问诊时间')),
                ('TETORESULT', models.CharField(blank=True, max_length=200, null=True, verbose_name='总问诊结果')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.Bed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人每日问诊',
            },
        ),
    ]
