# Generated by Django 2.0.5 on 2018-06-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BB_Ronghua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('BBCATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验分类')),
                ('BBRESULT', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验结果')),
                ('BBDATE', models.DateField(blank=True, null=True, verbose_name='检验时间')),
            ],
            options={
                'verbose_name_plural': '荣华婴儿表(ronghua_baby)',
                'db_table': 'ronghua_baby',
            },
        ),
        migrations.CreateModel(
            name='DM_Ronghua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('DMGENDER', models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性')], max_length=100, null=True, verbose_name='性别')),
                ('DMAGE', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('DMHEIGHT', models.IntegerField(blank=True, help_text='(cm)', null=True, verbose_name='身高')),
                ('DMWEIGHT', models.FloatField(blank=True, help_text='(kg)', null=True, verbose_name='体重')),
                ('DMSTDTC', models.DateField(blank=True, null=True, verbose_name='入院日期')),
                ('DMENDTC', models.DateField(blank=True, null=True, verbose_name='出院日期')),
                ('DMENTDIAG', models.CharField(blank=True, max_length=200, null=True, verbose_name='入院诊断')),
            ],
            options={
                'verbose_name_plural': '荣华病人基本信息(ronghua_demographic)',
                'db_table': 'ronghua_demographic',
            },
        ),
        migrations.CreateModel(
            name='EX_Ronghua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('EXDOSE', models.CharField(blank=True, max_length=200, null=True, verbose_name='每次用药剂量')),
                ('EXDOSEUNIT', models.CharField(blank=True, max_length=200, null=True, verbose_name='剂量单位')),
                ('EXDOCTYPE', models.CharField(blank=True, max_length=200, null=True, verbose_name='医嘱类型')),
                ('EXDATE', models.DateField(blank=True, null=True, verbose_name='给药日期')),
            ],
            options={
                'verbose_name_plural': '荣华用药记录(ronghua_exposure)',
                'db_table': 'ronghua_exposure',
            },
        ),
        migrations.CreateModel(
            name='NU_Ronghua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('NUCATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='护理分类')),
                ('NURESULT', models.CharField(blank=True, max_length=200, null=True, verbose_name='护理结果')),
                ('NUDATE', models.DateField(blank=True, null=True, verbose_name='护理时间')),
            ],
            options={
                'verbose_name_plural': '荣华护理记录(ronghua_nursing)',
                'db_table': 'ronghua_nursing',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('DMGENDER', models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性')], max_length=100, null=True, verbose_name='性别')),
                ('DMAGE', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('DMHEIGHT', models.IntegerField(blank=True, help_text='(cm)', null=True, verbose_name='身高')),
                ('DMWEIGHT', models.FloatField(blank=True, help_text='(kg)', null=True, verbose_name='体重')),
                ('DMSTDTC', models.DateField(blank=True, null=True, verbose_name='入院日期')),
                ('DMENDTC', models.DateField(blank=True, null=True, verbose_name='出院日期')),
            ],
            options={
                'verbose_name_plural': '病人基本信息(yiyuan_demographic)',
                'db_table': 'yiyuan_demographic',
            },
        ),
        migrations.CreateModel(
            name='PatientBed',
            fields=[
                ('bed_ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病床(yiyuan_bed)',
                'db_table': 'yiyuan_bed',
            },
        ),
        migrations.CreateModel(
            name='PatientEX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('EXDOSE', models.CharField(max_length=200, verbose_name='每次用药剂量')),
                ('EXDATE', models.DateField(blank=True, null=True, verbose_name='给药日期')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人用药记录(yiyuan_exposure)',
                'db_table': 'yiyuan_exposure',
            },
        ),
        migrations.CreateModel(
            name='PatientLB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('LBDATE', models.DateField(blank=True, null=True, verbose_name='检验时间')),
                ('LBCATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验分类')),
                ('LBSUCATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验子分类')),
                ('LBTEST', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验项目')),
                ('LBRESULT', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验结果')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人化验放射检验报告(yiyuan_laboratory)',
                'db_table': 'yiyuan_laboratory',
            },
        ),
        migrations.CreateModel(
            name='PatientMH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('MHDATE', models.DateField(blank=True, null=True, verbose_name='问诊时间')),
                ('MHPAST', models.CharField(blank=True, max_length=200, null=True, verbose_name='既往史')),
                ('MHPERSONAL', models.CharField(blank=True, max_length=200, null=True, verbose_name='个人史')),
                ('MHFAMILY', models.CharField(blank=True, max_length=200, null=True, verbose_name='家族史')),
                ('MHSSTATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='现病史（入院病症）')),
                ('MHESTATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='现病史（出院病症）')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人病史(yiyuan_med_history)',
                'db_table': 'yiyuan_med_history',
            },
        ),
        migrations.CreateModel(
            name='PatientPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('PETEST', models.CharField(max_length=200, verbose_name='体格检查名称')),
                ('PERESULT', models.CharField(max_length=200, verbose_name='体格检查结果')),
                ('PEDATE', models.DateField(verbose_name='体格检查日期')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人体格检验(yiyuan_physical_examination)',
                'db_table': 'yiyuan_physical_examination',
            },
        ),
        migrations.CreateModel(
            name='PatientPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('PRFIGE', models.BooleanField(verbose_name='是否手术')),
                ('PRCATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='手术类别')),
                ('PRDATE', models.DateField(blank=True, null=True, verbose_name='手术时间')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人手术状况(yiyuan_operation)',
                'db_table': 'yiyuan_operation',
            },
        ),
        migrations.CreateModel(
            name='PatientTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('TETEST', models.CharField(blank=True, max_length=200, null=True, verbose_name='每日检查项目')),
                ('TERESULT', models.CharField(blank=True, max_length=200, null=True, verbose_name='检查结果')),
                ('TEDATE', models.DateField(blank=True, null=True, verbose_name='问诊时间')),
                ('TETORESULT', models.CharField(blank=True, max_length=200, null=True, verbose_name='总问诊结果')),
                ('BEDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病人每日问诊(yiyuan_trial_element)',
                'db_table': 'yiyuan_trial_element',
            },
        ),
        migrations.CreateModel(
            name='PE_Ronghua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('PEOPT', models.BooleanField(verbose_name='是否手术')),
                ('PECATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验分类')),
                ('PERESULT', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验结果')),
                ('PEDATE', models.DateField(blank=True, null=True, verbose_name='检验时间')),
            ],
            options={
                'verbose_name_plural': '荣华体检表(ronghua_physical_examination)',
                'db_table': 'ronghua_physical_examination',
            },
        ),
        migrations.CreateModel(
            name='RonghuaBed',
            fields=[
                ('bed_ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '荣华病床(ronghua_bed)',
                'db_table': 'ronghua_bed',
            },
        ),
        migrations.AddField(
            model_name='pe_ronghua',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.RonghuaBed', verbose_name='床号'),
        ),
        migrations.AddField(
            model_name='patient',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号'),
        ),
        migrations.AddField(
            model_name='nu_ronghua',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.RonghuaBed', verbose_name='床号'),
        ),
        migrations.AddField(
            model_name='ex_ronghua',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.RonghuaBed', verbose_name='床号'),
        ),
        migrations.AddField(
            model_name='dm_ronghua',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.RonghuaBed', verbose_name='床号'),
        ),
        migrations.AddField(
            model_name='bb_ronghua',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.RonghuaBed', verbose_name='床号'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('BEDID', 'SUBJECTID')},
        ),
        migrations.AlterUniqueTogether(
            name='dm_ronghua',
            unique_together={('BEDID', 'SUBJECTID')},
        ),
    ]
