# Generated by Django 2.0.5 on 2018-05-24 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='serial_number',
            new_name='bed_name',
        ),
    ]
