# Generated by Django 2.0.5 on 2018-05-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BB_Ronghua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('BBCATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验分类')),
                ('BBRESULT', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验结果')),
                ('BBDATE', models.DateField(blank=True, null=True, verbose_name='检验时间')),
            ],
            options={
                'verbose_name_plural': '荣华婴儿表(BB_Ronghua)',
            },
        ),
        migrations.CreateModel(
            name='BT_Ronghua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('BTFIGE', models.BooleanField(verbose_name='是否手术')),
                ('BTCATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验分类')),
                ('BERESULT', models.CharField(blank=True, max_length=200, null=True, verbose_name='检验结果')),
                ('BEDATE', models.DateField(blank=True, null=True, verbose_name='护理时间')),
            ],
            options={
                'verbose_name_plural': '荣华体温表(BT_Ronghua)',
            },
        ),
        migrations.CreateModel(
            name='DM_Ronghua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('DMGENDER', models.CharField(blank=True, choices=[('F', '女性'), ('M', '男性')], max_length=100, null=True, verbose_name='性别')),
                ('DMAGE', models.IntegerField(blank=True, null=True, verbose_name='年龄')),
                ('DMHEIGHT', models.IntegerField(blank=True, help_text='(cm)', null=True, verbose_name='身高')),
                ('DMWEIGHT', models.FloatField(blank=True, help_text='(kg)', null=True, verbose_name='体重')),
                ('DMSTDTC', models.DateField(blank=True, null=True, verbose_name='入院日期')),
                ('DMENDTC', models.DateField(blank=True, null=True, verbose_name='出院日期')),
                ('DMENTDIAG', models.CharField(blank=True, max_length=200, null=True, verbose_name='入院诊断')),
            ],
            options={
                'verbose_name_plural': '荣华病人基本信息(DM_Ronghua)',
            },
        ),
        migrations.CreateModel(
            name='EX_Ronghua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('EXDOSE', models.CharField(blank=True, max_length=200, null=True, verbose_name='每次用药剂量')),
                ('EXDOSEUNIT', models.CharField(blank=True, max_length=200, null=True, verbose_name='剂量单位')),
                ('EXDOCTYPE', models.CharField(blank=True, max_length=200, null=True, verbose_name='医嘱类型')),
                ('EXDATE', models.DateField(blank=True, null=True, verbose_name='给药日期')),
            ],
            options={
                'verbose_name_plural': '荣华用药记录(EX_Ronghua)',
            },
        ),
        migrations.CreateModel(
            name='NU_Ronghua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SUBJECTID', models.IntegerField(verbose_name='病号')),
                ('NUCATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='护理分类')),
                ('NURESULT', models.CharField(blank=True, max_length=200, null=True, verbose_name='护理结果')),
                ('NUDATE', models.DateField(blank=True, null=True, verbose_name='护理时间')),
            ],
            options={
                'verbose_name_plural': '荣华护理记录(NU_Ronghua)',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ronghuapatient',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ronghuapatient',
            name='BEDID',
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': '病人基本信息(Patient)'},
        ),
        migrations.AlterModelOptions(
            name='patientbed',
            options={'verbose_name_plural': '病床(PatientBed)'},
        ),
        migrations.AlterModelOptions(
            name='patientex',
            options={'verbose_name_plural': '病人用药记录(PatientEX)'},
        ),
        migrations.AlterModelOptions(
            name='patientlb',
            options={'verbose_name_plural': '病人化验放射检验报告(PatientLB)'},
        ),
        migrations.AlterModelOptions(
            name='patientmh',
            options={'verbose_name_plural': '病人病史(PatientMH)'},
        ),
        migrations.AlterModelOptions(
            name='patientpe',
            options={'verbose_name_plural': '病人体格检验(PatientPE)'},
        ),
        migrations.AlterModelOptions(
            name='patientpr',
            options={'verbose_name_plural': '病人手术状况(PatientPR)'},
        ),
        migrations.AlterModelOptions(
            name='patientte',
            options={'verbose_name_plural': '病人每日问诊(PatientTE)'},
        ),
        migrations.AlterModelOptions(
            name='ronghuabed',
            options={'verbose_name_plural': '荣华智能床(RonghuaBed)'},
        ),
        migrations.DeleteModel(
            name='RonghuaPatient',
        ),
        migrations.AddField(
            model_name='nu_ronghua',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.RonghuaBed', verbose_name='智能床号'),
        ),
        migrations.AddField(
            model_name='ex_ronghua',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.RonghuaBed', verbose_name='智能床号'),
        ),
        migrations.AddField(
            model_name='dm_ronghua',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.RonghuaBed', verbose_name='智能床号'),
        ),
        migrations.AddField(
            model_name='bt_ronghua',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.RonghuaBed', verbose_name='智能床号'),
        ),
        migrations.AddField(
            model_name='bb_ronghua',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.RonghuaBed', verbose_name='智能床号'),
        ),
        migrations.AlterUniqueTogether(
            name='dm_ronghua',
            unique_together={('BEDID', 'SUBJECTID')},
        ),
    ]
