# Generated by Django 2.0.5 on 2018-05-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0002_auto_20180524_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='BEDID',
            field=models.IntegerField(verbose_name='床号'),
        ),
        migrations.AlterField(
            model_name='patientex',
            name='BEDID',
            field=models.IntegerField(verbose_name='床号'),
        ),
        migrations.AlterField(
            model_name='patientlb',
            name='BEDID',
            field=models.IntegerField(verbose_name='床号'),
        ),
        migrations.AlterField(
            model_name='patientmh',
            name='BEDID',
            field=models.IntegerField(verbose_name='床号'),
        ),
        migrations.AlterField(
            model_name='patientpe',
            name='BEDID',
            field=models.IntegerField(verbose_name='床号'),
        ),
        migrations.AlterField(
            model_name='patientpr',
            name='BEDID',
            field=models.IntegerField(verbose_name='床号'),
        ),
        migrations.AlterField(
            model_name='patientte',
            name='BEDID',
            field=models.IntegerField(verbose_name='床号'),
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
    ]
