# Generated by Django 2.0.5 on 2018-05-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0002_auto_20180528_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm_ronghua',
            name='DMGENDER',
            field=models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性')], max_length=100, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='DMGENDER',
            field=models.CharField(blank=True, choices=[('M', '男性'), ('F', '女性')], max_length=100, null=True, verbose_name='性别'),
        ),
    ]
