# Generated by Django 2.0.5 on 2018-06-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0003_auto_20180607_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dm_ronghua',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', '女性'), ('M', '男性')], max_length=64, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', '女性'), ('M', '男性')], max_length=64, null=True, verbose_name='性别'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=set(),
        ),
    ]
