# Generated by Django 2.0.5 on 2018-05-27 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0003_auto_20180525_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBed',
            fields=[
                ('bed_ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='床号')),
            ],
            options={
                'verbose_name_plural': '病床',
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号'),
        ),
        migrations.AlterField(
            model_name='patientex',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号'),
        ),
        migrations.AlterField(
            model_name='patientlb',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号'),
        ),
        migrations.AlterField(
            model_name='patientmh',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号'),
        ),
        migrations.AlterField(
            model_name='patientpe',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号'),
        ),
        migrations.AlterField(
            model_name='patientpr',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号'),
        ),
        migrations.AlterField(
            model_name='patientte',
            name='BEDID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontEnd.PatientBed', verbose_name='床号'),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('BEDID', 'SUBJECTID')},
        ),
    ]
