# Generated by Django 2.0.5 on 2018-06-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontEnd', '0004_auto_20180607_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='subject_id',
            field=models.IntegerField(verbose_name='病号'),
        ),
    ]
